[Config]
Profiles=generic,core,commonparts,vfat

[Content]
Bootable=no
Packages=kernel,grub2-efi,grub2-tools,grubby,grub2-common,grub-redpesk,dracut-redpesk-common
PostInstallationScripts=scripts/postinstall/50-kernelinstall-generic.sh.chroot

[Build]
Environment=REDPESK_BSP=redpesk-bsp
Environment=KERNEL_CMDLINE_EXTRA='cgroup_no_v1=all systemd.unified_cgroup_hierarchy=1 rw rootwait security=smack loglevel=7 fsck.mode=skip'
Environment=KERNEL_INSTALL_BYPASS=0

[Output]
RepartDirectories=repart.d/generic
