[Config]
Profiles=core,commonparts,vfat

[Content]
Bootable=no
Packages=arm-trusted-firmware,kernel,redpesk-bsp-repos-config,ti-linux-firmware,uboot

[Distribution]
Architecture=arm64

[Build]
Environment=REDPESK_BSP=beagleplay-bsp

[Output]
RepartDirectories=repart.d/texas-instruments