[Config]
Profiles=core,flash-uboot,commonparts,ubootscr

[Content]
Bootable=no
Packages=arm-trusted-firmware-imx8,kernel,redpesk-bsp-repos-config,uboot
SkeletonTrees=skeletons/imx8

[Distribution]
Architecture=arm64

[Build]
Environment=REDPESK_BSP=imx8-bsp
Environment=REDPESK_FLASH_BINS=/boot/flash.bin:bs=1024,seek=32,conv=notrunc

[Output]
RepartDirectories=repart.d/nxp/ext4