[Config]
Profiles=core,commonparts,ubootscr

[Content]
Bootable=no
Packages=arm-trusted-firmware,kernel
SkeletonTrees=skeletons/imx95

[Distribution]
Architecture=arm64

[Build]
Environment=REDPESK_BSP=imx95-bsp

[Output]
RepartDirectories=repart.d/nxp/ext4
