[Config]
Profiles=generic,core,commonparts,vfat

[Content]
Bootable=yes
Bootloader=grub
Packages=kernel,grub2-efi,grub2-tools,grubby,grub2-common
KernelCommandLineExtra='console=ttyS0 cgroup_no_v1=all systemd.unified_cgroup_hierarchy=1 rw rootwait security=smack loglevel=7 fsck.mode=skip'

[Build]
Environment=REDPESK_BSP=redpesk-bsp

[Output]
RepartDirectories=repart.d/generic
