[Config]
Profiles=core,flash-uboot,commonparts

[Content]
Bootable=no
Packages=kernel,redpesk-bsp-repos-config,qcacld-kmod,uboot,uboot-bootscripts

[Distribution]
Architecture=arm64

[Build]
Environment=REDPESK_BSP=nitrogen-bsp
Environment=REDPESK_FLASH_BINS=/boot/flash.bin:bs=1024,seek=32,conv=notrunc

[Output]
RepartDirectories=repart.d/nxp/ext4
