[Config]
Profiles=core,ubootsecurity,vfat,copykernelimage,commonparts,ubootscr

[Content]
Bootable=no
Packages=kernel,uboot,bcm2711-firmware,bcm2835-firmware
SkeletonTrees=skeletons/rpi

[Distribution]
Architecture=arm64

[Build]
Environment=REDPESK_BSP=rpi-bsp

[Output]
RepartDirectories=repart.d/rpi
