[Config]
Profiles=commonparts,vfat

[Content]
Bootable=no
Packages=arm-trusted-firmware,kernel,redpesk-bsp-repos-config,phytec-wireless-firmware,ti-linux-firmware,uboot

[Distribution]
Architecture=arm64

[Build]
Environment=REDPESK_BSP=phytec-bsp

[Output]
RepartDirectories=repart.d/texas-instruments