[Config]
Profiles=core,flash-uboot,commonparts,vfat,hybrid-mbr,ubootscr

[Content]
Bootable=no
Packages=arm-trusted-firmware,kernel,pfeng-driver,pfe-firmware,redpesk-bsp-repos-config,uboot
SkeletonTrees=skeletons/s32g2

[Distribution]
Architecture=arm64

[Build]
Environment=REDPESK_BSP=s32g2-bsp
Environment=ROOT_PART_NB=5
Environment=REDPESK_FLASH_BINS="/usr/lib/firmware/bl2_w_dtb.s32:bs=512;skip=8;seek=8;conv=notrunc,fsync /usr/lib/firmware/fip.bin:bs=512;seek=2048;conv=notrunc,fsync"
# for s32g2, ivt/bl2 ... need to be copied at offset 0x1000
# so table partition entries need to be reduced
Environment=GPT_RESIZE_TABLE_NB=16
Environment=REDPESK_HYBRID_MBR_PARTITIONS=1:0x83:0,2:0x0c:1

[Output]
RepartDirectories=repart.d/nxp/vfat
