[Config]
Profiles=core,commonparts

[Content]
Bootable=no
Packages=kernel,redpesk-bsp-repos-config

[Distribution]
Architecture=arm64

[Build]
Environment=REDPESK_BSP=renesas-gen3-bsp

[Output]
RepartDirectories=repart.d/renesas
