[Config]
Profiles=core,commonparts,vfat,flash-uboot

[Content]
Bootable=no
Packages=arm-trusted-firmware,kernel,phytec-wireless-firmware,uboot

[Distribution]
Architecture=arm64

[Build]
#Environment=REDPESK_BSP=phytec-imx8-bsp
Environment=REDPESK_FLASH_BINS=/boot/flash.bin:bs=1024,seek=32,conv=notrunc

[Output]
RepartDirectories=repart.d/nxp/vfat
