[Config]
Profiles=rpi,uboot,vfat

[Content]
Bootable=no
Packages=kernel,uboot,bcm2711-firmware,bcm2835-firmware

[Distribution]
Architecture=arm64

[Build]
Environment=REDPESK_BSP=rpi-bsp
Environment=REDPESK_FIX_FSTAB=1

[Output]
RepartDirectories=repart.d/rpi
