[Config]
Profiles=core,flash-uboot,commonparts

[Content]
Bootable=no
Packages=atf-firmware,configs-solidrun,kernel,redpesk-bsp-repos-config,solidrun-firmware,uboot

[Distribution]
Architecture=arm64

[Build]
Environment=REDPESK_BSP=solidrun-edge-gateways-bsp
Environment=REDPESK_FLASH_BINS=/boot/flash.bin:bs=1024,seek=32,conv=notrunc

[Output]
RepartDirectories=repart.d/solidrun/
