[Config]
Profiles=core,flash-uboot,commonparts,vfat,hybrid-mbr,ubootscr

[Content]
Bootable=no
Packages=arm-trusted-firmware,kernel,pfe-firmware,redpesk-bsp-repos-config,uboot
SkeletonTrees=skeletons/s32g2
# Ugly fix for dtb for now
PostInstallationScripts=scripts/postinstall/99-s32g2-fix-dtb.sh.chroot

[Distribution]
Architecture=arm64

[Build]
Environment=REDPESK_BSP=s32g2-bsp
Environment=ROOT_PART_NB=6
Environment=REDPESK_FLASH_BINS=/usr/lib/firmware/fip.s32:conv=notrunc,bs=512,seek=8,skip=8
# for s32g2, ivt/bl2/fip ... need to be copied at offset 0x1000
# so table partition entries need to be reduced
Environment=GPT_RESIZE_TABLE_NB=16
Environment=REDPESK_HYBRID_MBR_PARTITIONS=1:0x83:0,2:0x0c:1

[Output]
RepartDirectories=repart.d/nxp/vfat
