[Config]
Profiles=afb

[Include]
Include=mkosi.conf.d/afb-smack.conf
Include=mkosi.conf.d/afb-selinux.conf

[Content]
Packages=afb-app-manager,afb-app-manager-rpm,afb-binder
FinalizeScripts=scripts/finalize/50-afb-fix.sh.chroot

[Match]
Profiles=|afb


