[Content]
RemoveFiles=/etc/yum.repos.d/mkosi.repo
RootPassword=root

# default redpesk OS features
Locale=C.UTF-8
Timezone=Europe/Paris
Keymap=fr
PostInstallationScripts=scripts/postinstall/10-import-gpgkeys.sh.chroot

[Distribution]
Distribution=rocky
Release=9

[Validation]
Checksum=yes

[Build]
Environment=SYSTEMD_LOG_LEVEL=debug
