[Config]
Profiles=core

[Include]
Include=mkosi.conf.d/core.conf

[Content]
FinalizeScripts=scripts/finalize/50-manifest.sh
PostInstallationScripts=scripts/postinstall/50-binding-firstboot.sh
FinalizeScripts=scripts/finalize/50-boot.sh
PostOutputScripts=scripts/postoutput/99-redpesk.sh

[Output]
Format=disk
OutputDirectory=output

[Match]
Profiles=|core
