[Content]
RemoveFiles=/etc/yum.repos.d/mkosi.repo
RootPassword=root
ConfigureScripts=scripts/configure-fix-fstab.sh
FinalizeScripts=scripts/manifest.sh
PostOutputScripts=scripts/postoutput-redpesk.sh

[Distribution]
Distribution=rocky
Release=9

[Output]
Format=disk
OutputDirectory=output
Checksum=yes

[Build]
Environment=SYSTEMD_LOG_LEVEL=debug
