[Content]
RemoveFiles=/etc/yum.repos.d/mkosi.repo
RootPassword=root
ConfigureScripts=scripts/configure-fix-fstab.sh

[Distribution]
Distribution=rocky
Release=9

[Output]
Format=disk

[Build]
Environment=SYSTEMD_LOG_LEVEL=debug
