[Config]
Profiles=hybrid-mbr

[Build]
Environment=REDPESK_HYBRID_MBR=1
Environment=REDPESK_HYBRID_MBR_PARTITION=1
Environment=REDPESK_HYBRID_MBR_TYPE=0x0c
Environment=REDPESK_HYBRID_MBR_ACTIVE=1

[Match]
Profiles=hybrid-mbr

[Output]
RepartDirectories=repart.d/hybrid-mbr
