#!/usr/bin/env python3

# Create a hybrid MBR for a GPT image by exposing one GPT partition as an
# MBR partition and protecting the remaining GPT areas with 0xEE entries.
# This is intended for firmware/ROMs that only inspect the MBR but allows
# Linux to keep using the GPT layout generated by systemd-repart.

import argparse
import json
import os
import struct
import sys
from pathlib import Path


SECTOR_SIZE = 512
GPT_SIGNATURE = b"EFI PART"
MBR_SIGNATURE = b"\x55\xaa"


def die(message: str) -> None:
    print(f"hybrid-mbr: error: {message}", file=sys.stderr)
    sys.exit(1)


def parse_bool(value: str) -> bool:
    return value.strip().lower() not in ("", "0", "false", "no", "off")


def parse_int(value: str, name: str) -> int:
    try:
        return int(value, 0)
    except ValueError:
        die(f"invalid {name}: {value}")


def load_mkosi_output_name() -> str:
    config_path = os.environ.get("MKOSI_CONFIG")
    if not config_path:
        return "image"

    try:
        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)
    except FileNotFoundError:
        die(f"MKOSI_CONFIG does not exist: {config_path}")
    except json.JSONDecodeError as e:
        die(f"failed to parse MKOSI_CONFIG JSON: {e}")

    output = config.get("output", "image")
    if not isinstance(output, str) or not output:
        die("invalid 'output' value in MKOSI_CONFIG")

    return output


def default_image_path() -> str:
    output_dir = os.environ.get("OUTPUTDIR")
    if not output_dir:
        die("IMAGE argument is missing and OUTPUTDIR is not set")

    output_name = load_mkosi_output_name()
    return str(Path(output_dir) / f"{output_name}.raw")


def chs(lba: int) -> bytes:
    # Best-effort legacy CHS encoding. Modern firmware should use LBA fields.
    sectors = 63
    heads = 255
    max_lba = 1024 * heads * sectors

    if lba >= max_lba:
        return b"\xfe\xff\xff"

    cylinder = lba // (heads * sectors)
    tmp = lba % (heads * sectors)
    head = tmp // sectors
    sector = (tmp % sectors) + 1

    return bytes(
        [
            head & 0xFF,
            ((sector & 0x3F) | ((cylinder >> 2) & 0xC0)) & 0xFF,
            cylinder & 0xFF,
        ]
    )


def mbr_entry(bootable: bool, part_type: int, start_lba: int, size_lba: int) -> bytes:
    if not 0 <= part_type <= 0xFF:
        die(f"invalid MBR partition type: {part_type:#x}")
    if start_lba <= 0 or size_lba <= 0:
        die(f"invalid MBR range: start={start_lba}, size={size_lba}")
    if start_lba > 0xFFFFFFFF or size_lba > 0xFFFFFFFF:
        die("MBR cannot represent this partition range")

    end_lba = start_lba + size_lba - 1

    return struct.pack(
        "<B3sB3sII",
        0x80 if bootable else 0x00,
        chs(start_lba),
        part_type,
        chs(end_lba),
        start_lba,
        size_lba,
    )


def create_hybrid_mbr(
    image: str, partition_index: int, mbr_type: int, active: bool
) -> None:
    if partition_index < 1:
        die("partition index must be >= 1")

    image_size = os.path.getsize(image)
    if image_size % SECTOR_SIZE != 0:
        die(f"image size is not aligned on {SECTOR_SIZE} bytes")

    disk_lbas = image_size // SECTOR_SIZE

    with open(image, "r+b") as f:
        f.seek(SECTOR_SIZE)
        header = f.read(SECTOR_SIZE)

        if len(header) != SECTOR_SIZE or header[:8] != GPT_SIGNATURE:
            die("no primary GPT header found at LBA 1")

        current_lba = struct.unpack_from("<Q", header, 24)[0]
        entry_start_lba = struct.unpack_from("<Q", header, 72)[0]
        number_of_entries = struct.unpack_from("<I", header, 80)[0]
        entry_size = struct.unpack_from("<I", header, 84)[0]

        if current_lba != 1:
            die(f"unexpected primary GPT header LBA: {current_lba}")
        if partition_index > number_of_entries:
            die(f"partition {partition_index} does not exist in GPT")
        if entry_size < 128:
            die(f"unsupported GPT entry size: {entry_size}")

        entry_offset = (entry_start_lba * SECTOR_SIZE) + (
            (partition_index - 1) * entry_size
        )
        f.seek(entry_offset)
        entry = f.read(entry_size)

        if len(entry) != entry_size or entry[:16] == b"\x00" * 16:
            die(f"GPT partition {partition_index} is empty")

        first_lba = struct.unpack_from("<Q", entry, 32)[0]
        last_lba = struct.unpack_from("<Q", entry, 40)[0]

        if first_lba <= 1 or last_lba < first_lba or last_lba >= disk_lbas:
            die(f"invalid GPT partition range: first={first_lba}, last={last_lba}")

        entries = [
            mbr_entry(
                active,
                mbr_type,
                first_lba,
                last_lba - first_lba + 1,
            )
        ]

        # Protect the primary GPT header and entry array before the exposed partition.
        if first_lba > 1:
            entries.append(
                mbr_entry(
                    False,
                    0xEE,
                    1,
                    min(first_lba - 1, 0xFFFFFFFF),
                )
            )

        # Protect every GPT-only area after the exposed partition from MBR-only tools.
        after_start = last_lba + 1
        if after_start < disk_lbas and after_start <= 0xFFFFFFFF:
            entries.append(
                mbr_entry(
                    False,
                    0xEE,
                    after_start,
                    min(disk_lbas - after_start, 0xFFFFFFFF),
                )
            )

        if len(entries) > 4:
            die("internal error: too many MBR entries")

        table = b"".join(entries).ljust(16 * 4, b"\x00")

        f.seek(0)
        mbr = bytearray(f.read(SECTOR_SIZE))
        if len(mbr) != SECTOR_SIZE:
            die("unable to read MBR sector")

        # Preserve boot code and disk signature; replace only the partition table.
        mbr[446:510] = table
        mbr[510:512] = MBR_SIGNATURE

        f.seek(0)
        f.write(mbr)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a hybrid MBR for a GPT disk image.",
    )

    parser.add_argument(
        "image",
        nargs="?",
        help="Path to the GPT disk image. Defaults to OUTPUTDIR/<mkosi output>.raw.",
    )

    parser.add_argument(
        "--partition",
        default=os.environ.get("REDPESK_HYBRID_MBR_PARTITION", "1"),
        help="GPT partition index to expose in the MBR. Default: 1.",
    )

    parser.add_argument(
        "--mbr-type",
        default=os.environ.get("REDPESK_HYBRID_MBR_TYPE", "0x0c"),
        help="MBR partition type to use. Default: 0x0c.",
    )

    parser.add_argument(
        "--active",
        default=os.environ.get("REDPESK_HYBRID_MBR_ACTIVE", "1"),
        help="Whether to mark the exposed MBR partition as active. Default: 1.",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    image = args.image or default_image_path()
    partition_index = parse_int(args.partition, "partition")
    mbr_type = parse_int(args.mbr_type, "MBR type")
    active = parse_bool(args.active)

    create_hybrid_mbr(image, partition_index, mbr_type, active)

    print(
        f"hybrid-mbr: exposed GPT partition {partition_index} "
        f"as MBR type {mbr_type:#04x} in {image}"
    )


if __name__ == "__main__":
    main()
