#!/bin/bash

# Create a hybrid MBR for a GPT image by exposing one GPT partition as an
# MBR partition and protecting the remaining GPT areas with 0xEE entries.
# This is intended for firmware/ROMs that only inspect the MBR but allows
# Linux to keep using the GPT layout generated by systemd-repart.

set -euo pipefail

IMAGE=${1:-${OUTPUTDIR}/$(jq -r '.output // "image"' "$MKOSI_CONFIG").raw}
PARTITION=${REDPESK_HYBRID_MBR_PARTITION:-1}
MBR_TYPE=${REDPESK_HYBRID_MBR_TYPE:-0x0c}
ACTIVE=${REDPESK_HYBRID_MBR_ACTIVE:-1}
python3 - "$IMAGE" "$PARTITION" "$MBR_TYPE" "$ACTIVE" <<'PY'
import os
import struct
import sys

SECTOR_SIZE = 512
GPT_SIGNATURE = b"EFI PART"
MBR_SIGNATURE = b"\x55\xaa"


def die(message: str) -> None:
    print(f"hybrid-mbr: error: {message}", file=sys.stderr)
    sys.exit(1)


def parse_bool(value: str) -> bool:
    return value.strip().lower() not in ("", "0", "false", "no", "off")


def chs(lba: int) -> bytes:
    # Best-effort legacy CHS encoding. Modern firmware should use LBA fields.
    sectors = 63
    heads = 255
    max_lba = 1024 * heads * sectors

    if lba >= max_lba:
        return b"\xfe\xff\xff"

    cylinder = lba // (heads * sectors)
    tmp = lba % (heads * sectors)
    head = tmp // sectors
    sector = (tmp % sectors) + 1

    return bytes([
        head & 0xff,
        ((sector & 0x3f) | ((cylinder >> 2) & 0xc0)) & 0xff,
        cylinder & 0xff,
    ])


def mbr_entry(bootable: bool, part_type: int, start_lba: int, size_lba: int) -> bytes:
    if not 0 <= part_type <= 0xff:
        die(f"invalid MBR partition type: {part_type:#x}")
    if start_lba <= 0 or size_lba <= 0:
        die(f"invalid MBR range: start={start_lba}, size={size_lba}")
    if start_lba > 0xffffffff or size_lba > 0xffffffff:
        die("MBR cannot represent this partition range")

    end_lba = start_lba + size_lba - 1
    return struct.pack(
        "<B3sB3sII",
        0x80 if bootable else 0x00,
        chs(start_lba),
        part_type,
        chs(end_lba),
        start_lba,
        size_lba,
    )


if len(sys.argv) != 5:
    die("usage: 10-hybrid-mbr.sh IMAGE PARTITION MBR_TYPE ACTIVE")

image = sys.argv[1]
partition_index = int(sys.argv[2], 0)
mbr_type = int(sys.argv[3], 0)
active = parse_bool(sys.argv[4])

if partition_index < 1:
    die("partition index must be >= 1")

image_size = os.path.getsize(image)
if image_size % SECTOR_SIZE != 0:
    die(f"image size is not aligned on {SECTOR_SIZE} bytes")

disk_lbas = image_size // SECTOR_SIZE

with open(image, "r+b") as f:
    f.seek(SECTOR_SIZE)
    header = f.read(SECTOR_SIZE)

    if len(header) != SECTOR_SIZE or header[:8] != GPT_SIGNATURE:
        die("no primary GPT header found at LBA 1")

    current_lba = struct.unpack_from("<Q", header, 24)[0]
    entry_start_lba = struct.unpack_from("<Q", header, 72)[0]
    number_of_entries = struct.unpack_from("<I", header, 80)[0]
    entry_size = struct.unpack_from("<I", header, 84)[0]

    if current_lba != 1:
        die(f"unexpected primary GPT header LBA: {current_lba}")
    if partition_index > number_of_entries:
        die(f"partition {partition_index} does not exist in GPT")
    if entry_size < 128:
        die(f"unsupported GPT entry size: {entry_size}")

    entry_offset = (entry_start_lba * SECTOR_SIZE) + ((partition_index - 1) * entry_size)
    f.seek(entry_offset)
    entry = f.read(entry_size)

    if len(entry) != entry_size or entry[:16] == b"\x00" * 16:
        die(f"GPT partition {partition_index} is empty")

    first_lba = struct.unpack_from("<Q", entry, 32)[0]
    last_lba = struct.unpack_from("<Q", entry, 40)[0]

    if first_lba <= 1 or last_lba < first_lba or last_lba >= disk_lbas:
        die(f"invalid GPT partition range: first={first_lba}, last={last_lba}")

    entries = [mbr_entry(active, mbr_type, first_lba, last_lba - first_lba + 1)]

    # Protect the primary GPT header and entry array before the exposed partition.
    if first_lba > 1:
        entries.append(mbr_entry(False, 0xee, 1, min(first_lba - 1, 0xffffffff)))

    # Protect every GPT-only area after the exposed partition from MBR-only tools.
    after_start = last_lba + 1
    if after_start < disk_lbas and after_start <= 0xffffffff:
        entries.append(mbr_entry(False, 0xee, after_start, min(disk_lbas - after_start, 0xffffffff)))

    if len(entries) > 4:
        die("internal error: too many MBR entries")

    table = b"".join(entries).ljust(16 * 4, b"\x00")

    f.seek(0)
    mbr = bytearray(f.read(SECTOR_SIZE))
    if len(mbr) != SECTOR_SIZE:
        die("unable to read MBR sector")

    # Preserve boot code and disk signature; replace only the partition table.
    mbr[446:510] = table
    mbr[510:512] = MBR_SIGNATURE

    f.seek(0)
    f.write(mbr)

print(
    f"hybrid-mbr: exposed GPT partition {partition_index} "
    f"as MBR type {mbr_type:#04x} in {image}"
)
PY
