#!/usr/bin/env python3

# Create a hybrid MBR for a GPT image by exposing one GPT partition as an
# MBR partition and protecting the remaining GPT areas with 0xEE entries.
# This is intended for firmware/ROMs that only inspect the MBR but allows
# Linux to keep using the GPT layout generated by systemd-repart.

import argparse
import json
import os
import struct
import sys
from pathlib import Path


SECTOR_SIZE = 512
GPT_SIGNATURE = b"EFI PART"
MBR_SIGNATURE = b"\x55\xaa"


def die(message: str) -> None:
    print(f"hybrid-mbr: error: {message}", file=sys.stderr)
    sys.exit(1)


def parse_bool(value: str) -> bool:
    return value.strip().lower() not in ("", "0", "false", "no", "off")


def parse_int(value: str, name: str) -> int:
    try:
        return int(value, 0)
    except ValueError:
        die(f"invalid {name}: {value}")


def load_mkosi_output_name() -> str:
    config_path = os.environ.get("MKOSI_CONFIG")
    if not config_path:
        return "image"

    try:
        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)
    except FileNotFoundError:
        die(f"MKOSI_CONFIG does not exist: {config_path}")
    except json.JSONDecodeError as e:
        die(f"failed to parse MKOSI_CONFIG JSON: {e}")

    output = config.get("output", "image")
    if not isinstance(output, str) or not output:
        die("invalid 'output' value in MKOSI_CONFIG")

    return output


def default_image_path() -> str:
    output_dir = os.environ.get("OUTPUTDIR")
    if not output_dir:
        die("IMAGE argument is missing and OUTPUTDIR is not set")

    output_name = load_mkosi_output_name()
    return str(Path(output_dir) / f"{output_name}.raw")


def chs(lba: int) -> bytes:
    # Best-effort legacy CHS encoding. Modern firmware should use LBA fields.
    sectors = 63
    heads = 255
    max_lba = 1024 * heads * sectors

    if lba >= max_lba:
        return b"\xfe\xff\xff"

    cylinder = lba // (heads * sectors)
    tmp = lba % (heads * sectors)
    head = tmp // sectors
    sector = (tmp % sectors) + 1

    return bytes(
        [
            head & 0xFF,
            ((sector & 0x3F) | ((cylinder >> 2) & 0xC0)) & 0xFF,
            cylinder & 0xFF,
        ]
    )


def mbr_entry(bootable: bool, part_type: int, start_lba: int, size_lba: int) -> bytes:
    if not 0 <= part_type <= 0xFF:
        die(f"invalid MBR partition type: {part_type:#x}")
    if start_lba <= 0 or size_lba <= 0:
        die(f"invalid MBR range: start={start_lba}, size={size_lba}")
    if start_lba > 0xFFFFFFFF or size_lba > 0xFFFFFFFF:
        die("MBR cannot represent this partition range")

    end_lba = start_lba + size_lba - 1

    return struct.pack(
        "<B3sB3sII",
        0x80 if bootable else 0x00,
        chs(start_lba),
        part_type,
        chs(end_lba),
        start_lba,
        size_lba,
    )


def parse_partition_spec(value: str) -> tuple[int, int, bool]:
    fields = value.split(":")
    if len(fields) != 3:
        die(
            f"invalid hybrid partition specification: {value}; "
            "expected GPT_INDEX:MBR_TYPE:ACTIVE"
        )

    partition_index = parse_int(fields[0], "partition index")
    mbr_type = parse_int(fields[1], "MBR type")
    active = parse_bool(fields[2])

    if partition_index < 1:
        die("partition index must be >= 1")

    return partition_index, mbr_type, active


def parse_partition_specs(value: str) -> list[tuple[int, int, bool]]:
    specs = [item.strip() for item in value.split(",") if item.strip()]
    if not specs:
        die("hybrid partition list is empty")

    partitions = [parse_partition_spec(item) for item in specs]
    indexes = [partition[0] for partition in partitions]
    if len(indexes) != len(set(indexes)):
        die("the same GPT partition cannot be exposed more than once")
    if len(partitions) > 3:
        die("a hybrid MBR can expose at most 3 GPT partitions")

    return partitions


def create_hybrid_mbr(
    image: str, partitions: list[tuple[int, int, bool]]
) -> None:

    image_size = os.path.getsize(image)
    if image_size % SECTOR_SIZE != 0:
        die(f"image size is not aligned on {SECTOR_SIZE} bytes")

    disk_lbas = image_size // SECTOR_SIZE

    with open(image, "r+b") as f:
        f.seek(SECTOR_SIZE)
        header = f.read(SECTOR_SIZE)

        if len(header) != SECTOR_SIZE or header[:8] != GPT_SIGNATURE:
            die("no primary GPT header found at LBA 1")

        current_lba = struct.unpack_from("<Q", header, 24)[0]
        entry_start_lba = struct.unpack_from("<Q", header, 72)[0]
        number_of_entries = struct.unpack_from("<I", header, 80)[0]
        entry_size = struct.unpack_from("<I", header, 84)[0]

        if current_lba != 1:
            die(f"unexpected primary GPT header LBA: {current_lba}")
        if entry_size < 128:
            die(f"unsupported GPT entry size: {entry_size}")

        exposed = []
        for partition_index, mbr_type, active in partitions:
            if partition_index > number_of_entries:
                die(f"partition {partition_index} does not exist in GPT")

            entry_offset = (entry_start_lba * SECTOR_SIZE) + (
                (partition_index - 1) * entry_size
            )
            f.seek(entry_offset)
            entry = f.read(entry_size)

            if len(entry) != entry_size or entry[:16] == b"\x00" * 16:
                die(f"GPT partition {partition_index} is empty")

            first_lba = struct.unpack_from("<Q", entry, 32)[0]
            last_lba = struct.unpack_from("<Q", entry, 40)[0]

            if first_lba <= 1 or last_lba < first_lba or last_lba >= disk_lbas:
                die(
                    f"invalid GPT partition {partition_index} range: "
                    f"first={first_lba}, last={last_lba}"
                )

            exposed.append(
                (partition_index, mbr_type, active, first_lba, last_lba)
            )

        # Sort by disk position so the protective ranges are deterministic,
        # while keeping all exposed entries ahead of the 0xEE entries as before.
        exposed.sort(key=lambda partition: partition[3])

        for previous, current in zip(exposed, exposed[1:]):
            if current[3] <= previous[4]:
                die(
                    f"GPT partitions {previous[0]} and {current[0]} overlap"
                )

        entries = [
            mbr_entry(
                active,
                mbr_type,
                first_lba,
                last_lba - first_lba + 1,
            )
            for _, mbr_type, active, first_lba, last_lba in exposed
        ]

        first_exposed_lba = exposed[0][3]
        last_exposed_lba = exposed[-1][4]

        # The first protective entry must start at LBA 1 so GPT-aware tools
        # continue to recognize the disk as GPT. It protects the primary GPT
        # metadata and everything before the first exposed partition.
        if first_exposed_lba > 1:
            entries.append(
                mbr_entry(
                    False,
                    0xEE,
                    1,
                    min(first_exposed_lba - 1, 0xFFFFFFFF),
                )
            )

        # If an MBR slot remains, protect the tail of the disk too. Internal
        # gaps between exposed GPT partitions intentionally remain unrepresented:
        # an MBR has only four primary entries.
        after_start = last_exposed_lba + 1
        if (
            len(entries) < 4
            and after_start < disk_lbas
            and after_start <= 0xFFFFFFFF
        ):
            entries.append(
                mbr_entry(
                    False,
                    0xEE,
                    after_start,
                    min(disk_lbas - after_start, 0xFFFFFFFF),
                )
            )

        if len(entries) > 4:
            die(
                "not enough MBR entries for the requested hybrid partitions "
                "and the required GPT protective entry"
            )

        table = b"".join(entries).ljust(16 * 4, b"\x00")

        f.seek(0)
        mbr = bytearray(f.read(SECTOR_SIZE))
        if len(mbr) != SECTOR_SIZE:
            die("unable to read MBR sector")

        # Preserve boot code and disk signature; replace only the partition table.
        mbr[446:510] = table
        mbr[510:512] = MBR_SIGNATURE

        f.seek(0)
        f.write(mbr)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a hybrid MBR for a GPT disk image.",
    )

    parser.add_argument(
        "image",
        nargs="?",
        help="Path to the GPT disk image. Defaults to OUTPUTDIR/<mkosi output>.raw.",
    )

    parser.add_argument(
        "--partitions",
        default=os.environ.get("REDPESK_HYBRID_MBR_PARTITIONS"),
        help=(
            "Comma-separated GPT_INDEX:MBR_TYPE:ACTIVE entries to expose. "
            "Example: 1:0x83:0,2:0x0c:1. Overrides legacy --partition, "
            "--mbr-type and --active options."
        ),
    )

    parser.add_argument(
        "--partition",
        default=os.environ.get("REDPESK_HYBRID_MBR_PARTITION", "1"),
        help="GPT partition index to expose in the MBR. Default: 1.",
    )

    parser.add_argument(
        "--mbr-type",
        default=os.environ.get("REDPESK_HYBRID_MBR_TYPE", "0x0c"),
        help="MBR partition type to use. Default: 0x0c.",
    )

    parser.add_argument(
        "--active",
        default=os.environ.get("REDPESK_HYBRID_MBR_ACTIVE", "1"),
        help="Whether to mark the exposed MBR partition as active. Default: 1.",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    image = args.image or default_image_path()
    if args.partitions:
        partitions = parse_partition_specs(args.partitions)
    else:
        # Backward-compatible single-partition configuration.
        partition_index = parse_int(args.partition, "partition")
        mbr_type = parse_int(args.mbr_type, "MBR type")
        active = parse_bool(args.active)
        if partition_index < 1:
            die("partition index must be >= 1")
        partitions = [(partition_index, mbr_type, active)]

    create_hybrid_mbr(image, partitions)

    description = ", ".join(
        f"GPT {index} -> MBR {mbr_type:#04x}{' active' if active else ''}"
        for index, mbr_type, active in partitions
    )
    print(f"hybrid-mbr: exposed {description} in {image}")


if __name__ == "__main__":
    main()
