# Empty partition containing fip.bin (bootloader)
# Starting with the NXP's BSP version 48.0,
# it requires some space before this part
# for IVT + DTB + BL2
# FIP is loaded from the start of this part
# (2048 by default with systemd-repart for GPT)

[Partition]
Type=linux-generic
SizeMinBytes=8M
