# by default when efi partition: /boot is not copied into root partition
[Partition]
Type=linux-generic
Label=BOOT
Format=vfat
CopyFiles=/boot/:/
MountPoint=/boot/
ExcludeFiles=/boot/efi
SizeMinBytes=512M
